config/routes.rb
Maylogs::Application.routes.draw do
	
	resources :users
	
	resources :pages do
		collection do
			get 'new'
			post 'new_post'
			get 'edit_post'
			get 'delete_post'
			
		end
		
		member do
			get 'edit'
			get 'home_page'
			get 'display'
			get 'delete'
			post 'update'
		end
	end
	
	resources :sessions, only: [:new, :create, :destroy]
	
	root :to => 'static#home'

  get "static/home"
 
  get "static/search"
 
  get "static/reference"
 
  get "static/about"
	

	
	match 'reference', to: 'static#reference'
	match 'about', to: 'static#about'
	match 'signup', to: 'users#new'
	match 'log_in', to: 'sessions#new'
	match 'log_out', to: 'sessions#destroy'#, via: :delete

	
	
	match ':username/:id' => 'pages#display'
	match ':username' => 'pages#username_root'
	

	
	

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  username   :string(255)
#  title      :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base

	attr_accessible :email, :title, :username, :password, 
									:password_confirmation, :color
	has_secure_password
	
	has_many :pages, dependent: :destroy

	
	before_save { |user| user.email = email.downcase }
	before_save :create_remember_token
	
	VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
	VALID_USERNAME = /^\S*$/
	validates :title, presence: true, length: { maximum: 50 }
	validates :username, presence: true, uniqueness: true,
		 				length: { maximum: 50 }, format: {with: VALID_USERNAME}
	validates :email, presence: true, format: { with: VALID_EMAIL }, 
						uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }, confirmation: true
	validates :password_confirmation, presence: true
	
	
	def home_page
		self.pages.each do |page|
			@homepage = page if page.home
		end
		@homepage
	end
	
	def has_home?
		if self.home_page
			true
		else
			false
		end
	end
	
	private
		
		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end
	
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_filter :signed_in_user, only: [:edit, :show, :update]
	before_filter :correct_user, only: [:edit, :show, :update]
			## Show is included in these because
			## it's not being used as the profile;
			## it's user home page.
	
  def new
		if signed_in?
			flash[:error] = "You are already logged into an account."
			redirect_to root_url
		else
			@title = 'Sign Up'
			@page_id = 'sign_up'
			@user = User.new()
		end
  end
	
	def show
		@user = User.find(params[:id])
		@title = @user.title
		@page_id = "user_show"
	end
	
	def create
		@user = User.new(params[:user])
		@user.username.downcase
		
		if @user.save
			sign_in @user
			flash[:success] = 'Welcome to Maylogs!'
			redirect_to @user
		else
			@page_id = "sign_up"
			@title = 'Sign Up'
			render 'new'
		end
		
	end
	
	def edit
		@title = 'Settings'
		@page_id = 'settings'
		@user = User.find(params[:id])
	end
	
	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			flash[:success] = 'You have succcessfully changed your identity.'
			sign_in @user
			redirect_to @user
		else
			@title = 'Settings'
			@page_id = 'settings'
			render 'edit'
		end
	end
	
	private
		
		def signed_in_user
			unless signed_in?
				store_location
				redirect_to log_in_url
				flash[:error] = 'Please Sign In'
			end
		end
		
		def correct_user
			@user = User.find(params[:id])
			unless current_user?(@user)
				redirect_to root_url
				flash[:error] = 'You do not have permission to access that page.'
			end
		end
end

app/helpers/users_helper.rb
module UsersHelper
	
	def color_helper(user)
		if user.color
			user.color
		else
			"#1F75FE"
		end
	end
	
	
end

app/views/users/edit.html.erb
<h1><%= @title %></h1>

<div id = 'edit_form' class = 'basic_form'>
	
	<%= form_for(@user) do |f| %>
		
		<%= render 'shared/error_messages' %>
		
		<div><%= f.label :username %></div>
		<div><%= f.text_field :username, 
			placeholder: 'thebestblogever' %></div>
		
		<div><%= f.label :title, 'Blog Title' %></div>
		<div><%= f.text_field :title, 
			placeholder: 'The Best Blog Ever' %></div>

		<div><%= f.label :email %></div>
		<div><%= f.text_field :email %></div>
		
		<div><%= f.label :password %></div>
		<div><%= f.password_field :password %></div>
		
		<div><%= f.label :password_confirmation, 'Confirmation' %></div>
		<div><%= f.password_field :password_confirmation %></div>
		
		<div><%= f.label :color, 'Color Theme' %></div>
		<div><%= f.select(:color, [['Blue', '#1F75FE'], ['Green', '#9F3'], ['Orange', '#FFBF00'], ['Red', 'red'], ['Purple', '#9966CC'], ['Pink', '#FF007F'], ['Yellow', '#FFFF00']]) %></div>
		
		<%= f.submit "Change Identity", id: 'submit_button' %>
		
	<% end %>
</div>

app/views/users/new.html.erb
<h1><%= @title %></h1>

<div id = 'sign_up_form' class = 'basic_form'>
	
	<%= form_for(@user) do |f| %>
		
		<%= render 'shared/error_messages' %>
		
		<div><%= f.label :username %></div>
		<div><%= f.text_field :username, 
			placeholder: 'thebestblogever' %></div>
		
		<div><%= f.label :title, 'Blog Title' %></div>
		<div><%= f.text_field :title, 
			placeholder: 'The Best Blog Ever' %></div>

		<div><%= f.label :email %></div>
		<div><%= f.text_field :email %></div>
		
		<div><%= f.label :password %></div>
		<div><%= f.password_field :password %></div>
		
		<div><%= f.label :password_confirmation, 'Confirmation' %></div>
		<div><%= f.password_field :password_confirmation %></div>
		
		<%= f.submit "Jump Start", id: 'submit_button' %>
		
	<% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.title.split(" ").each { |t| t.capitalize }.join(' ') %></h1>

<nav id = 'edit_bar'>
	<li><div><%= link_to 'New Page', new_page_path,
		id: 'new_page_link' %></div></li>
	<li><div><%= link_to 'Delete', no_link_helper, 
		id: 'delete_button' %></div></li>
	<li><div><%= link_to 'Choose Home', no_link_helper, 
		id: 'home_button' %></div></li>
	<li><div><%= link_to 'Edit Page', no_link_helper,
		id: 'edit_button' %></div></li>
</nav>

<% unless @user.pages.any? %>

	<h3 style = 'text-align:center'>You do not have any pages yet.</h3>
	
	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
	
<% end %>

<%= render '/shared/page_thumbs' %>