config/routes.rb
Maylogs::Application.routes.draw do
	
	resources :users
	
	resources :pages do
		collection do
			get 'new'
			post 'new_post'
			get 'edit_post'
			get 'delete_post'
			
		end
		
		member do
			get 'edit'
			get 'home_page'
			get 'display'
			get 'delete'
			post 'update'
		end
	end
	
	resources :sessions, only: [:new, :create, :destroy]
	
	root :to => 'static#home'

  get "static/home"
 
  get "static/search"
 
  get "static/reference"
 
  get "static/about"
	

	
	match 'reference', to: 'static#reference'
	match 'about', to: 'static#about'
	match 'signup', to: 'users#new'
	match 'log_in', to: 'sessions#new'
	match 'log_out', to: 'sessions#destroy'#, via: :delete

	
	
	match ':username/:id' => 'pages#display'
	match ':username' => 'pages#username_root'
	

	
	

end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id = 'error_log'>
	<p>This form contains <%= pluralize @user.errors.count, 'error' %> 			</p>
	
	<ul>
		<% @user.errors.full_messages.each do |error| %>
			<% unless error =~ /digest/i %>
				<li><span class = 'error_designation'>*</span>
					 <%= error%></li><br />
			<% end %>
		<% end %>
	</ul>
	
</div>
<% end %>

app/views/shared/_page_error_messages.html.erb
<% if @page.errors.any? %>
<div id = 'error_log'>
	<p>This form contains <%= pluralize @page.errors.count, 'error' %> 			</p>
	
	<ul>
		<% @page.errors.full_messages.each do |error| %>
			<% unless error =~ /digest/i %>
				<li><span class = 'error_designation'>*</span>
					 <%= error%></li><br />
			<% end %>
		<% end %>
	</ul>
	
</div>
<% end %>

app/views/shared/_page_thumbs.html.erb
<% @user.pages.each do |page| %>
<div class = "page_thumb normal_thumb" id = "page_<%= page.id %>">

	<% unless page.home %>
		<%= link_to page_username_path(page), class: 'page_link'  do %>
		<div></div>
		<% end %>
	<% else %>
		<%= link_to username_path(page), class: 'page_link'  do %>
		<div></div>
		<% end %>
	<% end %>
	
	<span><%= page.title %></span>
	<div class = 'ex_line_out'>
		<div class = 'ex_line'></div>
	</div>
	<div class = 'page_image <% if page.home %>home_page_image<% end %>'>
		<div class = 'page_top_line'></div>
		<div class = 'page_line'></div>
		<div class = 'page_line'></div>
		<% if page.kind == 'blog' %>
		<div class = 'page_spacer'></div>
		<% end %>
		<div class = 'page_line'></div>
		<div class = 'page_line'></div>
	</div>
</div>
<% end %>