config/routes.rb
Maylogs::Application.routes.draw do
	
	resources :users
	
	resources :pages do
		collection do
			get 'new'
			post 'new_post'
			get 'edit_post'
			get 'delete_post'
			
		end
		
		member do
			get 'edit'
			get 'home_page'
			get 'display'
			get 'delete'
			post 'update'
		end
	end
	
	resources :sessions, only: [:new, :create, :destroy]
	
	root :to => 'static#home'

  get "static/home"
 
  get "static/search"
 
  get "static/reference"
 
  get "static/about"
	

	
	match 'reference', to: 'static#reference'
	match 'about', to: 'static#about'
	match 'signup', to: 'users#new'
	match 'log_in', to: 'sessions#new'
	match 'log_out', to: 'sessions#destroy'#, via: :delete

	
	
	match ':username/:id' => 'pages#display'
	match ':username' => 'pages#username_root'
	

	
	

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title_helper(@title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js' %>
  <%= javascript_include_tag "coffeescript" %>
  <%= csrf_meta_tags %>
</head>
<body id = "<%= @page_id %>_body">

	<header>
		
		<div id = 'line'></div>
		
		<h1><%= link_to 'MAYLOGS', root_path %></h1>
		
		<nav style = "<% if signed_in? %>right: 127px;<% end %>">
			<% if signed_in? %>
			
			<% end %>
			<li><%= link_to 'Reference', reference_path %></li>
			<li><%= link_to 'About', about_path %></li>
			<li><%= link_to 'Search', '#' %></li>
			<% unless signed_in? %>
			<li><%= link_to 'Log In', log_in_path %></li>
			<% else %>
			<li class = 'dropdown_trigger must_light_up'><%= link_to 'Account', '#' %></li>
			<div class = 'dropdown_trigger target_zone'></div>
			<ul class = 'dropdown'>
				<li><%= link_to 'Profile', username_path(current_user) %></li>
				<li><%= link_to 'Settings', edit_user_path(current_user) %></li>
				<div class = 'divider'></div>
				<li><%= link_to 'Log Out', log_out_path, method: 'delete' %></li>
			</ul>
			<% end %>
		</nav>
		
	</header>
	
	<% flash.each do |key, value| %>
	<div class = "flash flash-<%= key %>">
		<%= value %>
	</div>
	<% end %>
	

	<section id = "<%= @page_id %>">

	<%= yield %>

	</section>

  	<%# debug(params) if Rails.env.development? %>

	<footer>
		<div>
		
		<p>Copyright 2014 — <span>Charles Chamberlain</span><p>

		</div>
	</footer>

</body>
</html>